/*
 * The `--vscode-*` custom properties a real VS Code webview inherits, for the
 * two default themes. Values are VS Code's own colour-registry defaults (Dark+
 * / Light+), which are MIT-licensed. Nothing in extension/webview knows this
 * file exists — it only supplies the variables the stylesheet already reads.
 */
const COMMON = {
  'font-family': "-apple-system, BlinkMacSystemFont, 'Segoe UI', 'Ubuntu', 'Droid Sans', sans-serif",
  'font-size': '13px',
  'editor-font-family': "Menlo, Monaco, 'Courier New', monospace",
  'editor-font-size': '12px',
  'progressBar-background': '#0E70C0',
  'charts-orange': '#D18616',
  'panel-border': '#80808059',
};

const DARK = {
  ...COMMON,
  'editor-background': '#1E1E1E',
  'editor-foreground': '#D4D4D4',
  foreground: '#CCCCCC',
  descriptionForeground: '#CCCCCCB3',
  disabledForeground: '#CCCCCC80',
  focusBorder: '#007FD4',
  'sideBar-background': '#252526',
  'editorWidget-background': '#252526',
  'editorWidget-border': '#454545',
  'input-background': '#3C3C3C',
  'input-foreground': '#CCCCCC',
  'input-border': '#3C3C3C',
  'input-placeholderForeground': '#A6A6A6',
  'inputValidation-errorBackground': '#5A1D1D',
  'inputValidation-errorForeground': '#CCCCCC',
  'button-background': '#0E639C',
  'button-foreground': '#FFFFFF',
  'button-hoverBackground': '#1177BB',
  'button-border': '#FFFFFF12',
  'button-secondaryBackground': '#3A3D41',
  'button-secondaryForeground': '#FFFFFF',
  'button-secondaryHoverBackground': '#45494E',
  'textLink-foreground': '#3794FF',
  'textLink-activeForeground': '#3794FF',
  'editorError-foreground': '#F14C4C',
  'editorWarning-foreground': '#CCA700',
  'editorInfo-foreground': '#3794FF',
  'diffEditor-insertedTextBackground': '#9BB95533',
  'diffEditor-removedTextBackground': '#FF000033',
  'list-activeSelectionBackground': '#04395E',
  'list-activeSelectionForeground': '#FFFFFF',
  'list-hoverBackground': '#2A2D2E',
  'gitDecoration-addedResourceForeground': '#81B88B',
  'gitDecoration-deletedResourceForeground': '#C74E39',
};

const LIGHT = {
  ...COMMON,
  'editor-background': '#FFFFFF',
  'editor-foreground': '#000000',
  foreground: '#616161',
  descriptionForeground: '#717171',
  disabledForeground: '#61616180',
  focusBorder: '#0090F1',
  'sideBar-background': '#F3F3F3',
  'editorWidget-background': '#F3F3F3',
  'editorWidget-border': '#C8C8C8',
  'input-background': '#FFFFFF',
  'input-foreground': '#616161',
  'input-border': '#CECECE',
  'input-placeholderForeground': '#767676',
  'inputValidation-errorBackground': '#F2DEDE',
  'inputValidation-errorForeground': '#616161',
  'button-background': '#007ACC',
  'button-foreground': '#FFFFFF',
  'button-hoverBackground': '#0062A3',
  'button-border': '#00000012',
  'button-secondaryBackground': '#5F6A79',
  'button-secondaryForeground': '#FFFFFF',
  'button-secondaryHoverBackground': '#4C5561',
  'textLink-foreground': '#006AB1',
  'textLink-activeForeground': '#006AB1',
  'editorError-foreground': '#E51400',
  'editorWarning-foreground': '#BF8803',
  'editorInfo-foreground': '#1A85FF',
  'diffEditor-insertedTextBackground': '#9BB95533',
  'diffEditor-removedTextBackground': '#FF000033',
  'list-activeSelectionBackground': '#0060C0',
  'list-activeSelectionForeground': '#FFFFFF',
  'list-hoverBackground': '#E8E8E8',
  'gitDecoration-addedResourceForeground': '#587C0C',
  'gitDecoration-deletedResourceForeground': '#AD0707',
};

window.ComposureThemes = { dark: DARK, light: LIGHT };
